In [1]:
import torch

In [27]:
torch.arange(1, 4).unsqueeze(0).repeat(5,1)   #unsqueeze(1).size()

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [4]:
a=torch.tensor([[1, 2, 3], [4,5,6]])

In [5]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
a * a

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [7]:
a @ a.t()

tensor([[14, 32],
        [32, 77]])

In [8]:
a.repeat(1,1,2)

tensor([[[1, 2, 3, 1, 2, 3],
         [4, 5, 6, 4, 5, 6]]])

In [9]:
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [2]:
import minamp as mn

Un GPU est disponible


In [42]:
import importlib
importlib.reload(mn)

Un GPU est disponible


<module 'minamp' from 'c:\\Users\\herve\\OneDrive\\Projet\\MinAmp\\minamp.py'>

In [48]:
cadreExperimental=mn.CadreExperimental(nombrePhases=256,\
                premierePhase=12,\
                tailleSousEchantillons=64,\
                nombreSousEchantillons=64,
                tailleBatch=32)

Hardware utilisé : cuda:0
Métaparamètres: 256 phases (première 12), 64 sous échantillons de taille 64 (periode 1.0)


In [49]:
cadreExperimental.test_data.nombres.size()

torch.Size([4096])

In [50]:
cadreExperimental.training_data.__len__()

64

In [51]:
cadreExperimental.training_data.__getitem__(0)

(tensor([0.5569, 0.3770, 0.5085, 0.5842, 0.8125, 0.0505, 0.0078, 0.2717, 0.1721,
         0.4651, 0.6548, 0.4780, 0.1145, 0.2312, 0.9084, 0.3188, 0.4143, 0.1008,
         0.0042, 0.2461, 0.8250, 0.2339, 0.1594, 0.2407, 0.1458, 0.6184, 0.0608,
         0.3538, 0.8550, 0.8064, 0.6975, 0.4458, 0.2266, 0.7302, 0.8115, 0.0781,
         0.4185, 0.9111, 0.2676, 0.5112, 0.0403, 0.0627, 0.1921, 0.2175, 0.0867,
         0.8816, 0.8120, 0.2456, 0.6711, 0.4678, 0.9255, 0.8230, 0.9871, 0.1543,
         0.4065, 0.7129, 0.6167, 0.8364, 0.7158, 0.6802, 0.6125, 0.3274, 0.7065,
         0.5276]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [52]:
for b, (x,y) in enumerate(cadreExperimental.train_dataloader):
    print(b)
    print(x)
    print(y)

0
tensor([[0.5569, 0.3770, 0.5085,  ..., 0.3274, 0.7065, 0.5276],
        [0.6350, 0.2422, 0.0366,  ..., 0.1531, 0.8467, 0.8040],
        [0.0818, 0.7341, 0.0583,  ..., 0.4373, 0.1226, 0.1914],
        ...,
        [0.2051, 0.4058, 0.7402,  ..., 0.6484, 0.0977, 0.4233],
        [0.3391, 0.5232, 0.3811,  ..., 0.2002, 0.8274, 0.9438],
        [0.7959, 0.3542, 0.9744,  ..., 0.4490, 0.0410, 0.4775]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
1
tensor([[9.3774e-01, 7.0776e-01, 9.7607e-01,  ..., 8.9014e-01, 5.7544e-01,
         8.3008e-01],
        [3.7329e-01, 3.8550e-01, 8.5718e-01,  ..., 4.5190e-01, 3.9331e-01,
         1.2573e-01],
        [6.8115e-02, 9.6875e-01, 4.7290e-01,  ..., 8.3252e-02, 8.5107e-01,
         8.9429e-01],
        ...,
        [9.7046e-01, 9.3555e-01, 2.2607e

In [53]:
x.size()

torch.Size([32, 64])

In [26]:
cadreExperimental.model.Amplitudes

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [27]:
cadreExperimental.model.DeuxPiKSurT

tensor([[[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]],

        [[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]],

        [[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]],

        ...,

        [[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]],

        [[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]],

        [[   6.2832],
         [  12.5664],
         [  18.8496],
         ...,
         [1595.9291],
         [1602.2123],
         [1608.4955]]], device='cuda:0')

In [28]:
cadreExperimental.model.phase

Parameter containing:
tensor([[1.7216e+00],
        [3.7527e-01],
        [2.3198e+00],
        [5.1885e+00],
        [6.2315e-01],
        [3.0120e+00],
        [8.4378e-01],
        [3.6400e-01],
        [2.1346e+00],
        [5.1149e+00],
        [1.4247e+00],
        [5.9271e+00],
        [3.0739e+00],
        [4.9755e+00],
        [7.4423e-01],
        [6.1789e+00],
        [3.9764e+00],
        [3.7805e+00],
        [1.9617e+00],
        [2.6173e+00],
        [5.7618e+00],
        [2.9726e+00],
        [6.1483e+00],
        [1.0714e+00],
        [4.8036e+00],
        [9.2936e-01],
        [5.7173e+00],
        [5.1981e+00],
        [2.9328e+00],
        [2.2110e+00],
        [4.2156e+00],
        [5.6529e+00],
        [8.6562e-01],
        [2.5307e+00],
        [4.0561e+00],
        [6.0900e+00],
        [2.1386e+00],
        [5.8214e+00],
        [5.1678e+00],
        [5.0024e+00],
        [3.3505e+00],
        [1.5833e+00],
        [3.6195e-01],
        [4.1341e+00],
        [8

In [25]:
t=torch.arange(40).reshape(5,8)
t.unsqueeze_(1)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

        [[ 8,  9, 10, 11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20, 21, 22, 23]],

        [[24, 25, 26, 27, 28, 29, 30, 31]],

        [[32, 33, 34, 35, 36, 37, 38, 39]]])

In [26]:
DeuxPiKSurT = torch.arange(15).reshape(5,3)
DeuxPiKSurT.unsqueeze_(2)

tensor([[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]]])

In [27]:
print (t.size() , DeuxPiKSurT.size())

torch.Size([5, 1, 8]) torch.Size([5, 3, 1])


In [48]:
DeuxPiKSurT @ t

tensor([[[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   1,   2,   3,   4,   5,   6,   7],
         [  0,   2,   4,   6,   8,  10,  12,  14]],

        [[ 24,  27,  30,  33,  36,  39,  42,  45],
         [ 32,  36,  40,  44,  48,  52,  56,  60],
         [ 40,  45,  50,  55,  60,  65,  70,  75]],

        [[ 96, 102, 108, 114, 120, 126, 132, 138],
         [112, 119, 126, 133, 140, 147, 154, 161],
         [128, 136, 144, 152, 160, 168, 176, 184]],

        [[216, 225, 234, 243, 252, 261, 270, 279],
         [240, 250, 260, 270, 280, 290, 300, 310],
         [264, 275, 286, 297, 308, 319, 330, 341]],

        [[384, 396, 408, 420, 432, 444, 456, 468],
         [416, 429, 442, 455, 468, 481, 494, 507],
         [448, 462, 476, 490, 504, 518, 532, 546]]])

In [41]:
DeuxPiKSurT.matmul(t)

tensor([[[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   1,   2,   3,   4,   5,   6,   7],
         [  0,   2,   4,   6,   8,  10,  12,  14]],

        [[ 24,  27,  30,  33,  36,  39,  42,  45],
         [ 32,  36,  40,  44,  48,  52,  56,  60],
         [ 40,  45,  50,  55,  60,  65,  70,  75]],

        [[ 96, 102, 108, 114, 120, 126, 132, 138],
         [112, 119, 126, 133, 140, 147, 154, 161],
         [128, 136, 144, 152, 160, 168, 176, 184]],

        [[216, 225, 234, 243, 252, 261, 270, 279],
         [240, 250, 260, 270, 280, 290, 300, 310],
         [264, 275, 286, 297, 308, 319, 330, 341]],

        [[384, 396, 408, 420, 432, 444, 456, 468],
         [416, 429, 442, 455, 468, 481, 494, 507],
         [448, 462, 476, 490, 504, 518, 532, 546]]])

In [44]:
DeuxPiKSurT * t

tensor([[[  0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   1,   2,   3,   4,   5,   6,   7],
         [  0,   2,   4,   6,   8,  10,  12,  14]],

        [[ 24,  27,  30,  33,  36,  39,  42,  45],
         [ 32,  36,  40,  44,  48,  52,  56,  60],
         [ 40,  45,  50,  55,  60,  65,  70,  75]],

        [[ 96, 102, 108, 114, 120, 126, 132, 138],
         [112, 119, 126, 133, 140, 147, 154, 161],
         [128, 136, 144, 152, 160, 168, 176, 184]],

        [[216, 225, 234, 243, 252, 261, 270, 279],
         [240, 250, 260, 270, 280, 290, 300, 310],
         [264, 275, 286, 297, 308, 319, 330, 341]],

        [[384, 396, 408, 420, 432, 444, 456, 468],
         [416, 429, 442, 455, 468, 481, 494, 507],
         [448, 462, 476, 490, 504, 518, 532, 546]]])

In [87]:
torch.tensordot(t, DeuxPiKSurT, dims=([1, 0], [1, 0]))

RuntimeError: contracted dimensions need to match, but first has size 8 in dim 1 and second has size 3 in dim 1

In [88]:
torch.matmul(t, DeuxPiKSurT)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (5x8 and 5x3)